### ISSUE TITLE
Output is incomplete when using 'acm>help' 

### ISSUE THREAD

**Issue by xiaoyu3x** [nagineni/zjs-cli#7]
## Description
`acm>help` output information is incomplete.

## Steps to Reproduction
1.Run commands $ node zephyrjs-cli.js  -c 
2. acm>help

## Actual Result
![selection_027](https://user-images.githubusercontent.com/17694094/31807752-9675e50e-b5a2-11e7-94da-cc5f32e71e03.png)
There should be  'du' and 'parse' and remove 'eval'
## Expected Result
```
acm> help
Welcome to the ZJS 'A Shell' interface!

Command list:
    help           Display this help information
    run    FILE    Run the JavaScript program in the file
    parse  FILE    Check if the JS syntax is correct
    stop           Stop current JavaScript execution
    ls             List all files
    cat    FILE    Print the contents of a file
    du     FILE    Estimate file space usage
    rm     FILE    Remove file or directory
    mv     F1 F2   Move a file F1 to destination F2
    clear          Clear the terminal screen
    erase          Erase flash file system and reboot
    boot   FILE    Set the file that should run at boot
    reboot         Reboot the device
```

**Comment by xiaoyu3x** [comment]
Relatvie bug [#197](https://github.com/01org/zephyrjs-ide/issues/197)

**Comment by nagineni** [comment]
`load, parse` and `du` commands are skipped in the IDE image, so the actual outcome is correct in this case.

**Comment by xiaoyu3x** [comment]
@nagineni 
"eval" command can't be used, why it is displayed?

**Comment by nagineni** [comment]
`eval` command is there because we are using IDE image in CLI too. It is supported in IDE, but not in CLI.  There was an issue exiting with control character (i.e 'CTRL+D') once you enter into eval mode in the console (i.e CLI) and that's the reason the support is disabled.
